### ISSUE TITLE
rookpipe element of result table only contains most recent values

### ISSUE THREAD

**Issue by tercer** [TwoRavens/TwoRavens#211]
The `rookpipe` element of `allPipelineInfo` contains the dependent variable and predictors for building up a setx call.  However, it only contains the information for the latest `CreatePipelines` call.  The results table can accumulate results from multiple calls, presently. 

The four locations where this is presently a problem are all commented in this commit: b5ca844476900cc044bdbe97a35bd990e2a84c13

**Comment by Shoeboxam** [comment]
In experimental, rookpipe was replaced with a call to mongo. The response is N sampled records with column names `['d3mIndex', ...targets]`. The response is stored within the problem, and shared between all solutions for all solvers.

Since there is only one solver call per problem, the dvvalues will no longer be overwritten.
