### ISSUE TITLE
column naming inconsistency when converting "." to "_"

### ISSUE THREAD

**Issue by raprasad** [TwoRavens/TwoRavens#548]
- related: #560 

- When the reading datasetDoc from app.js, the column names have ".", e.g. "sunspot.year".  However, preprocess had loaded this all allNodes as "sunspot_year" 

**dataset**: 56_sunspots

**Comment by raprasad** [comment]
- [ ] move R special character renaming to python
  - [ ] sync column renaming with datasetDoc
- [ ] make python column renaming code into a primitive
- [ ] insert primitive into beginning of pipeline

**Comment by raprasad** [comment]
- this is related to a relatively recent update so that Mongo could deal with "." in the key name

**Comment by Shoeboxam** [comment]
How about instead of renaming columns globally/at the TA2 level, only rename columns within Mongo?
We could use this scheme:
https://stackoverflow.com/questions/12397118/mongodb-dot-in-key-name/30254815#30254815

There would be encoding upon ingest:
https://github.com/TwoRavens/TwoRavens/blob/aac9d51438f26aa4588ec67d99de7ed4f17835f2/tworaven_apps/eventdata_queries/event_job_util.py#L513

We would need to add encoding of fields used in the query, via the query reformatter here:
https://github.com/TwoRavens/TwoRavens/blob/aac9d51438f26aa4588ec67d99de7ed4f17835f2/tworaven_apps/eventdata_queries/mongo_retrieve_util.py#L102

We would need to add decoding of data fields here, after exhausting the cursor:
https://github.com/TwoRavens/TwoRavens/blob/aac9d51438f26aa4588ec67d99de7ed4f17835f2/tworaven_apps/eventdata_queries/mongo_retrieve_util.py#L209
