### ISSUE TITLE
Manipulation updates

### ISSUE THREAD

**Issue by raprasad** [TwoRavens/TwoRavens#592]
### notes

- Hide “+ Transform Step” button
	- Allow only subset and imputation (recode)
- Example: user subsets the data
  - Keep Mongo working "as is"
   - When Mongo call is successful, record/log the subset step in a UI object.  
      - e.g. `manipulation_steps` or similar`
   - When creating a searchSolutions call, add in the `manipulation_steps` 
      - primitive names can be added in UI or backend
- Modify/delete `manipulation_steps`  data as needed

### questions

- Save  `manipulation_steps` in raven_config?

**Comment by Shoeboxam** [comment]
In reference to this comment:
`When Mongo call is successful, record/log the subset step in a UI object.`

Assuming `problem 23` is selected, the existing system stores manipulations in the array `workspace.raven_config.problems['problem 23'].manipulations`. Said array contains abstract pipeline steps (objects describing the manipulation to be applied in each step).

The branch `592-d3m-manipulations` hides the appropriate buttons via `IS_D3M_DOMAIN` such that the manipulations pipeline is always expressible in D3M primitives. 

The relevant code to complete this issue is in `solvers/d3m.js/makePipelineTemplate`. In the branch, the code currently returns a pipeline template of malformed primitives that express user manipulations. This pipeline template is used in `app.estimate` for the endpoint `SearchDescribeFitScoreSolutions`.

The remaining steps are:

1. correcting the primitive specifications:
    a. Column Remover
    b. Numeric range filter
    c. Term list dataset filter
2. finding a recode primitive for imputations
