### ISSUE TITLE
ordinal tag

### ISSUE THREAD

**Issue by vjdorazio** [TwoRavens/TwoRavens#935]
the UI should allow users to tag a pebble as ordinal, and to specify the ordering of the categories. e.g., strongly disagree, disagree, indifferent, agree, strongly agree should be 1,2,3,4,5. the backend should use label encoding for ordinal variables, or never see the categorical variable and just get passed the numeric representation

**Comment by Shoeboxam** [comment]
I added a `ordinal` tag in cfc847c4f2044af8161924c1cc55aa860862956b.
- If the data is orderable, the ordinal tag is applied.
- If the data is not orderable, the user is asked if they want to provide an ordering. If they accept, a manipulations manual ordering transform menu is loaded with sensible defaults, so that the user just needs to supply numbers for each of the categories. By default, this manipulation overwrites the prior variable with the numeric ordering.
