### ISSUE TITLE
redesign right panel to load with subset

### ISSUE THREAD

**Issue by vjdorazio** [TwoRavens/TwoRavens#936]
redesign the right panel to load with a subset option, preloaded with a temporal variable. if no temporal variable, then either a categorical variable or the index. tuck the problem configuration menu away

**Comment by Shoeboxam** [comment]
You want to automatically apply a subset to the temporal variable? Are you thinking we never need all of the history?

When you start a new subset, I'll make it choose the previously selected manipulations variable by default (current behaviour). Otherwise, select temporal variable, if there is one. Otherwise, random.

**Comment by Shoeboxam** [comment]
I made manipulations load first. Closing because I don't think you intend to subset random data on load, by default.
